# Testing numpy library

## Install :

or get this command `pip install numpy` in your terminal

In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
# Using numpy and testing the library
print("Numpy was imported")

Numpy was imported


In [11]:
x = np.array([1, 2, 3])

In [7]:
# print first number in the array
print(np.array([1, 2, 3])[0])

1


In [12]:
y = np.array([3, 4, 5])

### Calculate 2 arrays

In [13]:
# calculate x array and y array
sumarray = x + y
# print the sum of the two arrays
print("The sum of arrays :", sumarray)

The sum of arrays : [4 6 8]


### 3D Array :

In [14]:
# 3d array
z = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [20]:
print("3D array:")
print(z)


3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
# advanced operations in numpy
def advancedoperations():
    # Create a 2D array
    a = np.array([[1, 2], [3, 4]])
    b = np.array([[5, 6], [7, 8]])

    # Matrix multiplication
    result = np.dot(a, b)
    print("Matrix multiplication result:")
    print(result)

    # Element-wise multiplication
    elementwise_result = a * b
    print("Element-wise multiplication result:")
    print(elementwise_result)

### Output :

In [30]:
print("Numpy array created successfully")
advancedoperations()

Numpy array created successfully
Matrix multiplication result:
[[19 22]
 [43 50]]
Element-wise multiplication result:
[[ 5 12]
 [21 32]]


#### Credits :

`0xSaad / Saad Almalki`
- [X](https://x.com/0xdonzdev)
- [Github](https://github.com/Saad711T)
- [LinkedIn](https://www.linkedin.com/in/saadalmalki711)
